# Generated by Django 4.2.27 on 2026-02-03 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("album", models.CharField(blank=True, max_length=200)),
                ("duration_seconds", models.IntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("cover_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.FloatField()),
                ("votes", models.IntegerField(default=0)),
                ("added_by", models.CharField(default="Anonymous", max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_playing", models.BooleanField(default=False)),
                ("played_at", models.DateTimeField(blank=True, null=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_items",
                        to="playlist.track",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
