# Generated by Django 4.2.27 on 2026-02-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistTrack',
        ),
    ]
