# Generated by Django 4.2.27 on 2026-02-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlisttrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='position',
        ),
    ]
