# Generated by Django 4.2.27 on 2026-02-08 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0004_remove_playlisttrack_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlisttrack',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_names', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
