# Generated by Django 4.2.27 on 2026-02-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
