# Generated by Django 4.2.27 on 2026-02-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
