# Generated by Django 4.2.27 on 2026-02-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_track_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlisttrack',
            name='played_at',
        ),
    ]
