# Generated by Django 4.2.27 on 2026-02-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0009_remove_playlisttrack_played_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('playlist_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='playlist.playlisttrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
